language: bash

before_script:
  - touch test

script:
  - export http_proxy=http://iss-americas-pitc-alpharettaz.proxy.corporate.ge.com:80/
  - export https_proxy=http://iss-americas-pitc-alpharettaz.proxy.corporate.ge.com:80/
  - export no_proxy="localhost, 127.0.0.1, *.ge.com"
  - curl -sSL https://get.rvm.io | bash -s stable
  - source /home/vagrant/.rvm/scripts/rvm
  - rvm install 2.0.0 --with-openssl-dir=$HOME/.rvm/usr
  - git --version
branches:
  only:
    - master

notifications:
  email:
    - dev@escapestudios.com
